name: Domus Ledger CI  Pipeline

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/docs'
      - '**/scripts'
      - 'README.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**/docs'
      - '**/scripts'
      - 'README.md'

env:
  DOTNET_VERSION: '9.0.x'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --no-restore --verbosity normal

